files:
  model_save_path : "trained_model.pt"
  train_path : "MLOpsProject/data/processed/train_loader.pth"
  test_path : "MLOpsProject/data/processed/test_loader.pth"
  val_path : "MLOpsProject/data/processed/val_loader.pth"


params:
  batch_size : 32
  epochs : 40
  debug_mode : False
  log_mode : True

optimizer:
   _target_: torch.optim.Adam
   lr: 9.6433e-05
    
loss:
    criterion : "torch.nn.modules.loss.CrossEntropyLoss"

model:
  model : models.model
  
