files:
  model_save_path : "trained_model.pt"

params:
  lr : 0.001
  batch_size : 10
  epochs : 5

optim:
  optimizer : "torch.optim.adam.Adam"

loss:
    criterion : "torch.nn.modules.loss.BCELoss"

model:
  model : models.model
  
