files:
  model_save_path : "trained_model.pt"
  train_path : "/data/processed/train_loader.pth"
  test_path : "/data/processed/test_loader.pth"
  val_path : "/data/processed/val_loader.pth"


params:
  lr: 1e-4
  batch_size : 10
  epochs : 20
  debug_mode : False
  log_mode : False

optimizer:
   _target_: torch.optim.Adam
   lr: 0.001
    
loss:
    criterion : "torch.nn.modules.loss.BCELoss"

model:
  model : models.model
  
